### ISSUE TITLE
Calendar Section Modifications and Typos

### ISSUE THREAD

**Issue by Jacob-Tellez** [ansuiuc/ansuiuc.github.io#12]
1. Can we replace the description with "This calendar is continually updated and contains dates for all confirmed ANS events, deadlines, and more. Interact with the calendar to find details on the location, time, and date of events. If you would like to suggest an event to host or for ANS to participate in, feel free to reach out to us!"

Thank you.

**Comment by JimmyGS14** [comment]
Fixed by Jacob's commit 10/6/18 b2ca4adf68e2ecbd5636cc9c4c306207b22f554e
